Email:
  #所测试服务描述
  service: KICP总后台
  #版本
  version: v2.1
  #测试人员
  tester: 小明
  #邮件备注
  remark: 请下载附件查看报告
  #是否发送邮件，on-发送，off-不发送
  is_send: on
  # 发件人邮箱
  user: 1036697284@qq.com
  # 发件人邮箱授权码
  password: kludwvejeviybcfd
  # 邮箱host
  host: smtp.qq.com
  # 收件人邮箱,linrq@kuaishang.cn,wuhui@kuaishang.com.cn,wujq@kuaishang.cn
  rec_users: ["wangl@kuaishang.cn"]

  title: xxx项目接口自动化测试报告


Mysql:
  db_host: 192.168.26.210
  db_port: 3306
  user_name: root
  user_pwd: kicp


Oracle:
  oracle_host: 192.168.26.171
  oracle_port: 1521
  oracle_user_name: onlinehd
  oracle_user_pwd: KstOracle120


ES:
  ip: http://192.168.1.15/
  port: 9200
  user_name: ''
  user_pwd: ''


SSH:
  ssh_ip: 192.168.1.97
  ssh_port: 2222
  ssh_name: '#GMdfh3TOGde'
  ssh_pwd: es123456


TEST-REDIS:
  redis_ip: 192.168.1.18
  redis_port: 6379


PRO-REDIS:
  redis_ip: 10.12.8.11
  redis_port: 6379


